import {
  index,
  integer,
  primaryKey,
  sqliteTable,
  text,
  uniqueIndex,
} from "drizzle-orm/sqlite-core";

/**
 * Bidroom database schema v1 (Drizzle, SQLite dialect on D1; ADR 0002). Account-scoped auth
 * ports moola's hardened model (session_version, hashed single-use tokens); workspaces,
 * memberships, and invitations are the net-new multi-tenant surface (ADR 0003). Timestamps
 * are ISO-8601 text, matching moola and keeping the rows portable. Ids are generated by the
 * application (randomToken), so primary keys are text.
 */

export const accounts = sqliteTable("accounts", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  locale: text("locale"),
  // Bumping session_version revokes every outstanding session for the account (ADR 0003).
  sessionVersion: integer("session_version").notNull().default(1),
  createdAt: text("created_at").notNull(),
});

export const authTokens = sqliteTable(
  "auth_tokens",
  {
    // Only the SHA-256 hash of the magic-link token is stored, never the token itself.
    tokenHash: text("token_hash").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    expiresAt: text("expires_at").notNull(),
    usedAt: text("used_at"),
  },
  (table) => [index("idx_auth_tokens_account").on(table.accountId)],
);

export const workspaces = sqliteTable("workspaces", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  workingLanguage: text("working_language").notNull().default("en"),
  createdBy: text("created_by")
    .notNull()
    .references(() => accounts.id),
  createdAt: text("created_at").notNull(),
});

export const memberships = sqliteTable(
  "memberships",
  {
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    role: text("role").notNull(),
    invitedBy: text("invited_by").references(() => accounts.id),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.accountId] }),
    index("idx_memberships_account").on(table.accountId),
  ],
);

export const invitations = sqliteTable(
  "invitations",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    // The invitation is bound to this email; acceptance requires the session account to match.
    email: text("email").notNull(),
    role: text("role").notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: text("expires_at").notNull(),
    acceptedAt: text("accepted_at"),
    invitedBy: text("invited_by")
      .notNull()
      .references(() => accounts.id),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    index("idx_invitations_workspace").on(table.workspaceId),
    index("idx_invitations_email").on(table.email),
  ],
);

export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  // Nullable for system-initiated actions; set for user and break-glass actions.
  actorAccountId: text("actor_account_id"),
  action: text("action").notNull(),
  objectType: text("object_type"),
  objectId: text("object_id"),
  reason: text("reason"),
  createdAt: text("created_at").notNull(),
});

/**
 * The qualification baseline for a workspace (WP-010). One per workspace. The list fields are
 * stored as JSON text (SQLite has no array type). profile_version is bumped on each save so an
 * analysis can record the profile version it used.
 */
export const companyProfiles = sqliteTable("company_profiles", {
  id: text("id").primaryKey(),
  workspaceId: text("workspace_id")
    .notNull()
    .unique()
    .references(() => workspaces.id, { onDelete: "cascade" }),
  capabilityTags: text("capability_tags", { mode: "json" }).$type<string[]>(),
  regions: text("regions", { mode: "json" }).$type<string[]>(),
  languages: text("languages", { mode: "json" }).$type<string[]>(),
  certifications: text("certifications", { mode: "json" }).$type<string[]>(),
  exclusions: text("exclusions", { mode: "json" }).$type<string[]>(),
  profileVersion: integer("profile_version").notNull().default(1),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

/**
 * An official SIMAP notice reference (WP-011). System-owned public data, shared across
 * workspaces if the same notice is opened twice. `raw_source` is the verbatim API JSON and is
 * never edited (LEG-002); the extracted fields are for display only. Keyed by the SIMAP
 * project + publication ids.
 */
export const tenderSourceItems = sqliteTable(
  "tender_source_items",
  {
    id: text("id").primaryKey(),
    simapProjectId: text("simap_project_id").notNull(),
    simapPublicationId: text("simap_publication_id").notNull(),
    simapUrl: text("simap_url").notNull(),
    authority: text("authority"),
    title: text("title"),
    procedureType: text("procedure_type"),
    publicationDate: text("publication_date"),
    rawSource: text("raw_source").notNull(),
    fetchedAt: text("fetched_at").notNull(),
  },
  (table) => [
    uniqueIndex("idx_tender_source_notice").on(table.simapProjectId, table.simapPublicationId),
  ],
);

/**
 * A tender case in a workspace (WP-011), tenant-scoped. References the official source item;
 * findings, files, and decisions attach to it in later work packages.
 */
export const dossiers = sqliteTable(
  "dossiers",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    sourceItemId: text("source_item_id")
      .notNull()
      .references(() => tenderSourceItems.id),
    title: text("title").notNull(),
    status: text("status").notNull().default("draft"),
    createdBy: text("created_by")
      .notNull()
      .references(() => accounts.id),
    createdAt: text("created_at").notNull(),
  },
  (table) => [index("idx_dossiers_workspace").on(table.workspaceId)],
);

/**
 * A document uploaded to a dossier (WP-012). The bytes live in R2; this row is the registry.
 * `scan_status` records the fail-closed malware scan (R-SCAN-04): bytes are stored only after a
 * clean scan. `status` records the outcome (stored, unsupported, too_large, failed). The
 * workspace_id is denormalized for tenant-scoped queries.
 */
export const uploadedFiles = sqliteTable(
  "uploaded_files",
  {
    id: text("id").primaryKey(),
    dossierId: text("dossier_id")
      .notNull()
      .references(() => dossiers.id, { onDelete: "cascade" }),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    filename: text("filename").notNull(),
    mime: text("mime"),
    size: integer("size").notNull(),
    sha256: text("sha256"),
    category: text("category").notNull().default("tender"),
    scanStatus: text("scan_status").notNull().default("pending"),
    status: text("status").notNull(),
    createdBy: text("created_by")
      .notNull()
      .references(() => accounts.id),
    createdAt: text("created_at").notNull(),
  },
  (table) => [index("idx_uploaded_files_dossier").on(table.dossierId)],
);
