import { index, integer, primaryKey, sqliteTable, text } from "drizzle-orm/sqlite-core";

/**
 * Bidroom database schema v1 (Drizzle, SQLite dialect on D1; ADR 0002). Account-scoped auth
 * ports moola's hardened model (session_version, hashed single-use tokens); workspaces,
 * memberships, and invitations are the net-new multi-tenant surface (ADR 0003). Timestamps
 * are ISO-8601 text, matching moola and keeping the rows portable. Ids are generated by the
 * application (randomToken), so primary keys are text.
 */

export const accounts = sqliteTable("accounts", {
  id: text("id").primaryKey(),
  email: text("email").notNull().unique(),
  name: text("name"),
  locale: text("locale"),
  // Bumping session_version revokes every outstanding session for the account (ADR 0003).
  sessionVersion: integer("session_version").notNull().default(1),
  createdAt: text("created_at").notNull(),
});

export const authTokens = sqliteTable(
  "auth_tokens",
  {
    // Only the SHA-256 hash of the magic-link token is stored, never the token itself.
    tokenHash: text("token_hash").primaryKey(),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    expiresAt: text("expires_at").notNull(),
    usedAt: text("used_at"),
  },
  (table) => [index("idx_auth_tokens_account").on(table.accountId)],
);

export const workspaces = sqliteTable("workspaces", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  workingLanguage: text("working_language").notNull().default("en"),
  createdBy: text("created_by")
    .notNull()
    .references(() => accounts.id),
  createdAt: text("created_at").notNull(),
});

export const memberships = sqliteTable(
  "memberships",
  {
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    accountId: text("account_id")
      .notNull()
      .references(() => accounts.id, { onDelete: "cascade" }),
    role: text("role").notNull(),
    invitedBy: text("invited_by").references(() => accounts.id),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.workspaceId, table.accountId] }),
    index("idx_memberships_account").on(table.accountId),
  ],
);

export const invitations = sqliteTable(
  "invitations",
  {
    id: text("id").primaryKey(),
    workspaceId: text("workspace_id")
      .notNull()
      .references(() => workspaces.id, { onDelete: "cascade" }),
    // The invitation is bound to this email; acceptance requires the session account to match.
    email: text("email").notNull(),
    role: text("role").notNull(),
    tokenHash: text("token_hash").notNull().unique(),
    expiresAt: text("expires_at").notNull(),
    acceptedAt: text("accepted_at"),
    invitedBy: text("invited_by")
      .notNull()
      .references(() => accounts.id),
    createdAt: text("created_at").notNull(),
  },
  (table) => [
    index("idx_invitations_workspace").on(table.workspaceId),
    index("idx_invitations_email").on(table.email),
  ],
);

export const auditEvents = sqliteTable("audit_events", {
  id: text("id").primaryKey(),
  // Nullable for system-initiated actions; set for user and break-glass actions.
  actorAccountId: text("actor_account_id"),
  action: text("action").notNull(),
  objectType: text("object_type"),
  objectId: text("object_id"),
  reason: text("reason"),
  createdAt: text("created_at").notNull(),
});
